site_name: ElkPlot

theme:
  "material"

nav:
- Home: index.md
- About: about.md
- API Reference:
    - Making Art: api_ref/making_art.md
    - Controlling the Plotter: api_ref/plotting.md

plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          show_root_toc_entry: false

watch:
- elkplot